id: opecha:P007112
initial_creation_type: ocr
source_metadata:
  id: bdr:W22084
  title: བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽
  volume:
    9b15e7ab78fb40b2bcd4e3a47c37e204:
      image_group_id: I0886
      title: ''
      volume_number: 1
      total_pages: 624
    85bca2c2a05a4526be90a0fca7b749dd:
      image_group_id: I0887
      title: ''
      volume_number: 2
      total_pages: 636
    d169cc4a7b4345438c003acfe6d66631:
      image_group_id: I0888
      title: ''
      volume_number: 3
      total_pages: 588
    e6a67eb0657a41409ad45ce267450fda:
      image_group_id: I0889
      title: ''
      volume_number: 4
      total_pages: 606
    304b9b149aae49f7987fb8be8988b65b:
      image_group_id: I0890
      title: ''
      volume_number: 5
      total_pages: 586
    4c5866276c8643cc9712c081dfdfe789:
      image_group_id: I0891
      title: ''
      volume_number: 6
      total_pages: 577
    7807010c48d2452894e0401bc1886d35:
      image_group_id: I0892
      title: ''
      volume_number: 7
      total_pages: 576
    b26cc51048c34cee8396c3f9cc874ea4:
      image_group_id: I0893
      title: ''
      volume_number: 8
      total_pages: 540
    a2b5f5f0777d4f459264123a7ecf6b25:
      image_group_id: I0894
      title: ''
      volume_number: 9
      total_pages: 658
    db6e5d71159a4674ae1a2b58abbf2ae0:
      image_group_id: I0895
      title: ''
      volume_number: 10
      total_pages: 622
    02adf0606834464499b8a622e5cfa07c:
      image_group_id: I0896
      title: ''
      volume_number: 11
      total_pages: 668
    762c4ef3deb24598823937793dfc8846:
      image_group_id: I0897
      title: ''
      volume_number: 12
      total_pages: 606
    facf3aaca0c943e781fdc70e53785800:
      image_group_id: I0898
      title: ''
      volume_number: 13
      total_pages: 628
    bb55bd4ffce44251968588aad60a7df4:
      image_group_id: I0899
      title: ''
      volume_number: 14
      total_pages: 790
    f9b94bdc27434b4687795cbced568bd0:
      image_group_id: I0900
      title: ''
      volume_number: 15
      total_pages: 806
    f400bc9fc0ee4aaab653cd1b2e7d69a0:
      image_group_id: I0901
      title: ''
      volume_number: 16
      total_pages: 790
    8ab1f0b7fada4c91933ad9451d03410e:
      image_group_id: I0902
      title: ''
      volume_number: 17
      total_pages: 764
    b076a15cece24607bbac6ae31eda4b6e:
      image_group_id: I0903
      title: ''
      volume_number: 18
      total_pages: 792
    6952d1c24ad74d6881da0bb56c08531c:
      image_group_id: I0904
      title: ''
      volume_number: 19
      total_pages: 766
    02f0ffcf67aa42f4863ec671b309ec51:
      image_group_id: I0905
      title: ''
      volume_number: 20
      total_pages: 798
    b7a44a1119664a26b38dd9c252b12523:
      image_group_id: I0906
      title: ''
      volume_number: 21
      total_pages: 800
    8ecc85e7a245419ba08778b93f4c7559:
      image_group_id: I0907
      title: ''
      volume_number: 22
      total_pages: 770
    b5e2f6ad53b5419ba7e271ba88232ec1:
      image_group_id: I0908
      title: ''
      volume_number: 23
      total_pages: 776
    47bb61b33cd44108aa2ce656a83a26de:
      image_group_id: I0909
      title: ''
      volume_number: 24
      total_pages: 824
    25a4aa76cac341a8bb349318a702c6c0:
      image_group_id: I0910
      title: ''
      volume_number: 25
      total_pages: 792
    b13c860874c14ec8a073a96cc3cc9c6c:
      image_group_id: I0911
      title: ''
      volume_number: 26
      total_pages: 766
    38cb0db4716140ed9458fd673a2ef5ef:
      image_group_id: I0912
      title: ''
      volume_number: 27
      total_pages: 788
    47372ce00f45487eb6be174179c39c69:
      image_group_id: I0913
      title: ''
      volume_number: 28
      total_pages: 764
    979ef8db40934eee8ff5a6689083cd73:
      image_group_id: I0914
      title: ''
      volume_number: 29
      total_pages: 602
    efbfa7069f3343a7aa32a704e557af92:
      image_group_id: I0915
      title: ''
      volume_number: 30
      total_pages: 610
    f60c17a296c845139b0637bb161155e3:
      image_group_id: I0916
      title: ''
      volume_number: 31
      total_pages: 596
    cbfa4d3e7acc4d67ac949ceca8e06dbe:
      image_group_id: I0917
      title: ''
      volume_number: 32
      total_pages: 614
    b1c79ece6b5f423cafe02ff2e26794be:
      image_group_id: I0918
      title: ''
      volume_number: 33
      total_pages: 574
    5d60932e403f4a61ab3602928d5e02b4:
      image_group_id: I0919
      title: ''
      volume_number: 34
      total_pages: 569
    b9bd5a43e4c44f13a3054e512444486a:
      image_group_id: I0920
      title: ''
      volume_number: 35
      total_pages: 788
    7be7e20aec824177ad99f5e0a58fc3f1:
      image_group_id: I0921
      title: ''
      volume_number: 36
      total_pages: 794
    9ebfd0f7927042bf808c22bb50836ae9:
      image_group_id: I0922
      title: ''
      volume_number: 37
      total_pages: 794
    24e99b9db8ef46d48f991e0e7f7b6404:
      image_group_id: I0923
      title: ''
      volume_number: 38
      total_pages: 728
    dc7f42c5df934f8093835d0fa5ea69d8:
      image_group_id: I0924
      title: ''
      volume_number: 39
      total_pages: 542
    f23301ab1ee84b1b8ea0046b32fed701:
      image_group_id: I0925
      title: ''
      volume_number: 40
      total_pages: 590
    63b15dab48144e959b1cb7889dbb8e65:
      image_group_id: I0926
      title: ''
      volume_number: 41
      total_pages: 598
    d44f1e2c209b43c9a62e876be032c1fd:
      image_group_id: I0927
      title: ''
      volume_number: 42
      total_pages: 578
    7e1c7bf152bc4bf7b6529cd4db477cf6:
      image_group_id: I0928
      title: ''
      volume_number: 43
      total_pages: 620
    d2ab257dcd5e4348b8a5694febdeb43f:
      image_group_id: I0929
      title: ''
      volume_number: 44
      total_pages: 600
    1941cda8d98a436b802a039ea92427bb:
      image_group_id: I0930
      title: ''
      volume_number: 45
      total_pages: 682
    207707e26ce74aea91833598425d4c6b:
      image_group_id: I0931
      title: ''
      volume_number: 46
      total_pages: 558
    b2922a03a3734a4789b2af0f46f0cc6f:
      image_group_id: I0932
      title: ''
      volume_number: 47
      total_pages: 612
    2aff8fcad6dc488cb7490d8a75520b85:
      image_group_id: I0933
      title: ''
      volume_number: 48
      total_pages: 576
    ab0b61e2607b4e29bf25acc34f5dd05a:
      image_group_id: I0934
      title: ''
      volume_number: 49
      total_pages: 586
    2e199cfb39274215864621aa28122f4f:
      image_group_id: I0935
      title: ''
      volume_number: 50
      total_pages: 594
    3d0e37eab7ba4a18879bfe3b387edd42:
      image_group_id: I0936
      title: ''
      volume_number: 51
      total_pages: 598
    320b23f946f04a339ee87accd6b26776:
      image_group_id: I0937
      title: ''
      volume_number: 52
      total_pages: 688
    b43a71235cc5484d82dc07653d5b471d:
      image_group_id: I0938
      title: ''
      volume_number: 53
      total_pages: 680
    43b6c699753c4b68a2b011ffeda4db45:
      image_group_id: I0939
      title: ''
      volume_number: 54
      total_pages: 594
    adbb50f76f584d4f9055f3c4efba0f17:
      image_group_id: I0940
      title: ''
      volume_number: 55
      total_pages: 634
    328651fa62bf472686abb17a4952a49f:
      image_group_id: I0941
      title: ''
      volume_number: 56
      total_pages: 602
    62c8de89cd9243a9af91fa0c177c6e47:
      image_group_id: I0942
      title: ''
      volume_number: 57
      total_pages: 690
    f2dc77f168e441c08c8d417775e47a7f:
      image_group_id: I0943
      title: ''
      volume_number: 58
      total_pages: 640
    fd17f388ed7e47df8f464d1bd038c563:
      image_group_id: I0944
      title: ''
      volume_number: 59
      total_pages: 630
    5cd203439f5b4fe0b10cb9481a56e8ae:
      image_group_id: I0945
      title: ''
      volume_number: 60
      total_pages: 594
    b0697a1c423646278d9cdf36ee6857ab:
      image_group_id: I0946
      title: ''
      volume_number: 61
      total_pages: 618
    9788192231704863a0bd198bf5d75495:
      image_group_id: I0947
      title: ''
      volume_number: 62
      total_pages: 616
    3dce6af8a2bf473ba9eb35827f4b2138:
      image_group_id: I0948
      title: ''
      volume_number: 63
      total_pages: 596
    36f15ce8ba914ba0acfdfa99ce6766e3:
      image_group_id: I0949
      title: ''
      volume_number: 64
      total_pages: 600
    80ec56da0f1e44b2bb8bdf9193ad8ec9:
      image_group_id: I0950
      title: ''
      volume_number: 65
      total_pages: 614
    505a21388afd4af2859e1a38ab364ed2:
      image_group_id: I0951
      title: ''
      volume_number: 66
      total_pages: 622
    ef07fdc286a14ef284c8def14a567c50:
      image_group_id: I0952
      title: ''
      volume_number: 67
      total_pages: 640
    b51e8425c6964191b294bc7741d087d5:
      image_group_id: I0953
      title: ''
      volume_number: 68
      total_pages: 638
    c2932e5731a34a779076c07e797fa1d5:
      image_group_id: I0954
      title: ''
      volume_number: 69
      total_pages: 616
    b6e2fa8cc27345149d1f844809eb5ab9:
      image_group_id: I0955
      title: ''
      volume_number: 70
      total_pages: 626
    0b62979c0fcb4c4a9a088e0ba7425b4c:
      image_group_id: I0956
      title: ''
      volume_number: 71
      total_pages: 612
    c14f5b64ef9341ebb2351e5de34630fd:
      image_group_id: I0957
      title: ''
      volume_number: 72
      total_pages: 622
    a5659e85e45d496e98ee5851c60f4249:
      image_group_id: I0958
      title: ''
      volume_number: 73
      total_pages: 620
    f2110390daaa4d1a80a82478fd33443c:
      image_group_id: I0959
      title: ''
      volume_number: 74
      total_pages: 602
    c177dcb70d99440a9eb20183fbf88247:
      image_group_id: I0960
      title: ''
      volume_number: 75
      total_pages: 598
    afadb6e9f7ca4d10a4114e519651cf2a:
      image_group_id: I0961
      title: ''
      volume_number: 76
      total_pages: 564
    a46d4d8c182c46cbba137e205c089e00:
      image_group_id: I0962
      title: ''
      volume_number: 77
      total_pages: 742
    b45359f7d82d412a9a8311b9ece9bd88:
      image_group_id: I0963
      title: ''
      volume_number: 78
      total_pages: 624
    9f9658c8febc4db19a6f2ee84c518850:
      image_group_id: I0964
      title: ''
      volume_number: 79
      total_pages: 586
    e9551418accc405b972697478b662091:
      image_group_id: I0965
      title: ''
      volume_number: 80
      total_pages: 688
    487e363cab9b4d5bb8d7115cb563b247:
      image_group_id: I0966
      title: ''
      volume_number: 81
      total_pages: 574
    656e9dccd73b4da18093b3d26da46db7:
      image_group_id: I0967
      title: ''
      volume_number: 82
      total_pages: 664
    decac9ecff0f4d8ba4a708cb16e6fc73:
      image_group_id: I0968
      title: ''
      volume_number: 83
      total_pages: 608
    534b46af55bc4415a480f65981aa505a:
      image_group_id: I0969
      title: ''
      volume_number: 84
      total_pages: 550
    0e47f39d2c4742e0b9c9b2b4897860d1:
      image_group_id: I0970
      title: ''
      volume_number: 85
      total_pages: 546
    ac94b031937240528d0037b16246f74c:
      image_group_id: I0971
      title: ''
      volume_number: 86
      total_pages: 648
    93cea45c4a974d929f31a57c15292da3:
      image_group_id: I0972
      title: ''
      volume_number: 87
      total_pages: 620
    2b177c2f492043919b95a28d479f719f:
      image_group_id: I0973
      title: ''
      volume_number: 88
      total_pages: 670
    fef4b14e79ba4fe5a10e9f4a729b5392:
      image_group_id: I0974
      title: ''
      volume_number: 89
      total_pages: 548
    ffd210ab8b18450782a5eac260a72c60:
      image_group_id: I0975
      title: ''
      volume_number: 90
      total_pages: 574
    5b04afa529fc4634a1f8bec17b071a54:
      image_group_id: I0976
      title: ''
      volume_number: 91
      total_pages: 576
    ec6abb0f28e34797ae2cdbc884935a4f:
      image_group_id: I0977
      title: ''
      volume_number: 92
      total_pages: 634
    7172c70fd74449d791cfce8b62e4ca24:
      image_group_id: I0978
      title: ''
      volume_number: 93
      total_pages: 622
    db09d46c01ee40c9a4f704acce44bc62:
      image_group_id: I0979
      title: ''
      volume_number: 94
      total_pages: 534
    285ca556c49c4ea8bddb681010246b05:
      image_group_id: I0980
      title: ''
      volume_number: 95
      total_pages: 592
    54f164136a5c4133ad37926b70da1bb1:
      image_group_id: I0981
      title: ''
      volume_number: 96
      total_pages: 530
    3ff455931b46486e811db421f4f172c7:
      image_group_id: I0982
      title: ''
      volume_number: 97
      total_pages: 718
    606adbe59a6d4664bd63aa2dda81b7b1:
      image_group_id: I0983
      title: ''
      volume_number: 98
      total_pages: 624
    765fe1e037624c3593676a09c909c8ed:
      image_group_id: I0984
      title: ''
      volume_number: 99
      total_pages: 576
    8df361b1b2dd493aa82c14baaf16d82c:
      image_group_id: I0985
      title: ''
      volume_number: 100
      total_pages: 568
    14553c857e03407b98ace096f3367e57:
      image_group_id: I0986
      title: ''
      volume_number: 101
      total_pages: 558
    2e8dfa231b3840869784ed5f92439db7:
      image_group_id: I0987
      title: ''
      volume_number: 102
      total_pages: 944
    85f7d604c28d4adbaa57b688cd359731:
      image_group_id: I0988
      title: ''
      volume_number: 103
      total_pages: 344
  author: ''
ebook_metadata:
  title: བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽
  author: ''
  sku: P007112
  cover: cover.jpg
  layers:
  - pagination
