id: I6440489A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:49:18+00:00'
last_modified: '2022-06-09T05:33:57.031710+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22084
  title: བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    700A:
      image_group_id: I0886
      title: ''
      total_pages: 624
      order: 1
      base_file: 700A.txt
    C4E4:
      image_group_id: I0887
      title: ''
      total_pages: 636
      order: 2
      base_file: C4E4.txt
    343F:
      image_group_id: I0888
      title: ''
      total_pages: 588
      order: 3
      base_file: 343F.txt
    '4260':
      image_group_id: I0889
      title: ''
      total_pages: 606
      order: 4
      base_file: 4260.txt
    8E25:
      image_group_id: I0890
      title: ''
      total_pages: 586
      order: 5
      base_file: 8E25.txt
    '3048':
      image_group_id: I0891
      title: ''
      total_pages: 577
      order: 6
      base_file: 3048.txt
    BC49:
      image_group_id: I0892
      title: ''
      total_pages: 576
      order: 7
      base_file: BC49.txt
    F972:
      image_group_id: I0893
      title: ''
      total_pages: 540
      order: 8
      base_file: F972.txt
    0C01:
      image_group_id: I0894
      title: ''
      total_pages: 658
      order: 9
      base_file: 0C01.txt
    C060:
      image_group_id: I0895
      title: ''
      total_pages: 622
      order: 10
      base_file: C060.txt
    7BCD:
      image_group_id: I0896
      title: ''
      total_pages: 668
      order: 11
      base_file: 7BCD.txt
    D2B7:
      image_group_id: I0897
      title: ''
      total_pages: 606
      order: 12
      base_file: D2B7.txt
    AEDD:
      image_group_id: I0898
      title: ''
      total_pages: 628
      order: 13
      base_file: AEDD.txt
    '7238':
      image_group_id: I0899
      title: ''
      total_pages: 790
      order: 14
      base_file: 7238.txt
    E161:
      image_group_id: I0900
      title: ''
      total_pages: 806
      order: 15
      base_file: E161.txt
    A53B:
      image_group_id: I0901
      title: ''
      total_pages: 790
      order: 16
      base_file: A53B.txt
    935B:
      image_group_id: I0902
      title: ''
      total_pages: 764
      order: 17
      base_file: 935B.txt
    F4D0:
      image_group_id: I0903
      title: ''
      total_pages: 792
      order: 18
      base_file: F4D0.txt
    AC4A:
      image_group_id: I0904
      title: ''
      total_pages: 766
      order: 19
      base_file: AC4A.txt
    D447:
      image_group_id: I0905
      title: ''
      total_pages: 798
      order: 20
      base_file: D447.txt
    '5799':
      image_group_id: I0906
      title: ''
      total_pages: 800
      order: 21
      base_file: 5799.txt
    93BA:
      image_group_id: I0907
      title: ''
      total_pages: 770
      order: 22
      base_file: 93BA.txt
    602F:
      image_group_id: I0908
      title: ''
      total_pages: 776
      order: 23
      base_file: 602F.txt
    '1075':
      image_group_id: I0909
      title: ''
      total_pages: 824
      order: 24
      base_file: 1075.txt
    358A:
      image_group_id: I0910
      title: ''
      total_pages: 792
      order: 25
      base_file: 358A.txt
    23E4:
      image_group_id: I0911
      title: ''
      total_pages: 766
      order: 26
      base_file: 23E4.txt
    F0F4:
      image_group_id: I0912
      title: ''
      total_pages: 788
      order: 27
      base_file: F0F4.txt
    '7871':
      image_group_id: I0913
      title: ''
      total_pages: 764
      order: 28
      base_file: 7871.txt
    CCC2:
      image_group_id: I0914
      title: ''
      total_pages: 602
      order: 29
      base_file: CCC2.txt
    2D55:
      image_group_id: I0915
      title: ''
      total_pages: 610
      order: 30
      base_file: 2D55.txt
    B11B:
      image_group_id: I0916
      title: ''
      total_pages: 596
      order: 31
      base_file: B11B.txt
    1DE6:
      image_group_id: I0917
      title: ''
      total_pages: 614
      order: 32
      base_file: 1DE6.txt
    C401:
      image_group_id: I0918
      title: ''
      total_pages: 574
      order: 33
      base_file: C401.txt
    EE0F:
      image_group_id: I0919
      title: ''
      total_pages: 569
      order: 34
      base_file: EE0F.txt
    D0C6:
      image_group_id: I0920
      title: ''
      total_pages: 788
      order: 35
      base_file: D0C6.txt
    9E77:
      image_group_id: I0921
      title: ''
      total_pages: 794
      order: 36
      base_file: 9E77.txt
    F162:
      image_group_id: I0922
      title: ''
      total_pages: 794
      order: 37
      base_file: F162.txt
    '4654':
      image_group_id: I0923
      title: ''
      total_pages: 728
      order: 38
      base_file: 4654.txt
    A26E:
      image_group_id: I0924
      title: ''
      total_pages: 542
      order: 39
      base_file: A26E.txt
    5E14:
      image_group_id: I0925
      title: ''
      total_pages: 590
      order: 40
      base_file: 5E14.txt
    FCAE:
      image_group_id: I0926
      title: ''
      total_pages: 598
      order: 41
      base_file: FCAE.txt
    FF92:
      image_group_id: I0927
      title: ''
      total_pages: 578
      order: 42
      base_file: FF92.txt
    '7784':
      image_group_id: I0928
      title: ''
      total_pages: 620
      order: 43
      base_file: 7784.txt
    '6418':
      image_group_id: I0929
      title: ''
      total_pages: 600
      order: 44
      base_file: 6418.txt
    B04F:
      image_group_id: I0930
      title: ''
      total_pages: 682
      order: 45
      base_file: B04F.txt
    '6864':
      image_group_id: I0931
      title: ''
      total_pages: 558
      order: 46
      base_file: 6864.txt
    575B:
      image_group_id: I0932
      title: ''
      total_pages: 612
      order: 47
      base_file: 575B.txt
    '1073':
      image_group_id: I0933
      title: ''
      total_pages: 576
      order: 48
      base_file: 1073.txt
    348D:
      image_group_id: I0934
      title: ''
      total_pages: 586
      order: 49
      base_file: 348D.txt
    5B99:
      image_group_id: I0935
      title: ''
      total_pages: 594
      order: 50
      base_file: 5B99.txt
    '5444':
      image_group_id: I0936
      title: ''
      total_pages: 598
      order: 51
      base_file: 5444.txt
    '7952':
      image_group_id: I0937
      title: ''
      total_pages: 688
      order: 52
      base_file: 7952.txt
    8A83:
      image_group_id: I0938
      title: ''
      total_pages: 680
      order: 53
      base_file: 8A83.txt
    B74B:
      image_group_id: I0939
      title: ''
      total_pages: 594
      order: 54
      base_file: B74B.txt
    FEBC:
      image_group_id: I0940
      title: ''
      total_pages: 634
      order: 55
      base_file: FEBC.txt
    '2405':
      image_group_id: I0941
      title: ''
      total_pages: 602
      order: 56
      base_file: 2405.txt
    04E8:
      image_group_id: I0942
      title: ''
      total_pages: 690
      order: 57
      base_file: 04E8.txt
    B4EE:
      image_group_id: I0943
      title: ''
      total_pages: 640
      order: 58
      base_file: B4EE.txt
    1F7F:
      image_group_id: I0944
      title: ''
      total_pages: 630
      order: 59
      base_file: 1F7F.txt
    C7CB:
      image_group_id: I0945
      title: ''
      total_pages: 594
      order: 60
      base_file: C7CB.txt
    '7559':
      image_group_id: I0946
      title: ''
      total_pages: 618
      order: 61
      base_file: 7559.txt
    44AA:
      image_group_id: I0947
      title: ''
      total_pages: 616
      order: 62
      base_file: 44AA.txt
    '6940':
      image_group_id: I0948
      title: ''
      total_pages: 596
      order: 63
      base_file: 6940.txt
    99ED:
      image_group_id: I0949
      title: ''
      total_pages: 600
      order: 64
      base_file: 99ED.txt
    '3441':
      image_group_id: I0950
      title: ''
      total_pages: 614
      order: 65
      base_file: 3441.txt
    86D4:
      image_group_id: I0951
      title: ''
      total_pages: 622
      order: 66
      base_file: 86D4.txt
    7CCB:
      image_group_id: I0952
      title: ''
      total_pages: 640
      order: 67
      base_file: 7CCB.txt
    12DF:
      image_group_id: I0953
      title: ''
      total_pages: 638
      order: 68
      base_file: 12DF.txt
    '5569':
      image_group_id: I0954
      title: ''
      total_pages: 616
      order: 69
      base_file: 5569.txt
    4A70:
      image_group_id: I0955
      title: ''
      total_pages: 626
      order: 70
      base_file: 4A70.txt
    441B:
      image_group_id: I0956
      title: ''
      total_pages: 612
      order: 71
      base_file: 441B.txt
    CD99:
      image_group_id: I0957
      title: ''
      total_pages: 622
      order: 72
      base_file: CD99.txt
    DEF4:
      image_group_id: I0958
      title: ''
      total_pages: 620
      order: 73
      base_file: DEF4.txt
    '4483':
      image_group_id: I0959
      title: ''
      total_pages: 602
      order: 74
      base_file: 4483.txt
    2EBD:
      image_group_id: I0960
      title: ''
      total_pages: 598
      order: 75
      base_file: 2EBD.txt
    D4BA:
      image_group_id: I0961
      title: ''
      total_pages: 564
      order: 76
      base_file: D4BA.txt
    4AF0:
      image_group_id: I0962
      title: ''
      total_pages: 742
      order: 77
      base_file: 4AF0.txt
    '1682':
      image_group_id: I0963
      title: ''
      total_pages: 624
      order: 78
      base_file: 1682.txt
    F04F:
      image_group_id: I0964
      title: ''
      total_pages: 586
      order: 79
      base_file: F04F.txt
    F43C:
      image_group_id: I0965
      title: ''
      total_pages: 688
      order: 80
      base_file: F43C.txt
    B548:
      image_group_id: I0966
      title: ''
      total_pages: 574
      order: 81
      base_file: B548.txt
    EE4B:
      image_group_id: I0967
      title: ''
      total_pages: 664
      order: 82
      base_file: EE4B.txt
    3CD0:
      image_group_id: I0968
      title: ''
      total_pages: 608
      order: 83
      base_file: 3CD0.txt
    CFF1:
      image_group_id: I0969
      title: ''
      total_pages: 550
      order: 84
      base_file: CFF1.txt
    DE42:
      image_group_id: I0970
      title: ''
      total_pages: 546
      order: 85
      base_file: DE42.txt
    '8677':
      image_group_id: I0971
      title: ''
      total_pages: 648
      order: 86
      base_file: 8677.txt
    44C1:
      image_group_id: I0972
      title: ''
      total_pages: 620
      order: 87
      base_file: 44C1.txt
    747E:
      image_group_id: I0973
      title: ''
      total_pages: 670
      order: 88
      base_file: 747E.txt
    3CAE:
      image_group_id: I0974
      title: ''
      total_pages: 548
      order: 89
      base_file: 3CAE.txt
    13D4:
      image_group_id: I0975
      title: ''
      total_pages: 574
      order: 90
      base_file: 13D4.txt
    96B5:
      image_group_id: I0976
      title: ''
      total_pages: 576
      order: 91
      base_file: 96B5.txt
    ECE3:
      image_group_id: I0977
      title: ''
      total_pages: 634
      order: 92
      base_file: ECE3.txt
    61CC:
      image_group_id: I0978
      title: ''
      total_pages: 622
      order: 93
      base_file: 61CC.txt
    A7A5:
      image_group_id: I0979
      title: ''
      total_pages: 534
      order: 94
      base_file: A7A5.txt
    BFF4:
      image_group_id: I0980
      title: ''
      total_pages: 592
      order: 95
      base_file: BFF4.txt
    8EE4:
      image_group_id: I0981
      title: ''
      total_pages: 530
      order: 96
      base_file: 8EE4.txt
    61C9:
      image_group_id: I0982
      title: ''
      total_pages: 718
      order: 97
      base_file: 61C9.txt
    462B:
      image_group_id: I0983
      title: ''
      total_pages: 624
      order: 98
      base_file: 462B.txt
    D779:
      image_group_id: I0984
      title: ''
      total_pages: 576
      order: 99
      base_file: D779.txt
    E390:
      image_group_id: I0985
      title: ''
      total_pages: 568
      order: 100
      base_file: E390.txt
    6A23:
      image_group_id: I0986
      title: ''
      total_pages: 558
      order: 101
      base_file: 6A23.txt
    3AB0:
      image_group_id: I0987
      title: ''
      total_pages: 944
      order: 102
      base_file: 3AB0.txt
    70F8:
      image_group_id: I0988
      title: ''
      total_pages: 344
      order: 103
      base_file: 70F8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
